export interface SourceHint {
  short: string;
  detail?: string;
  pitfall?: string;
  source: string;
}

const SOURCE_HINTS: Record<string, SourceHint> = {
  '1': {
    short: 'Een onbewerkt splintertje is klein, toevallig gevormd en toont geen doelgerichte retouche of kernstructuur.',
    detail: 'De bron gebruikt deze vroege vraag om microsplinters en triviale fragmenten uit te sluiten voordat de echte determinatie begint.',
    pitfall: 'Een klein artefact kan nog steeds bewerkt zijn; kijk dus eerst naar retouche, slagvlak en negatieven.',
    source: 'Algoritme vraag 1, handleiding basisuitsluiting splinters',
  },
  '2': {
    short: 'Controleer of het gat echt kunstmatig is geboord of gepikt en niet natuurlijk ontstaan.',
    detail: 'Een niet-natuurlijk gat opent direct de route naar doorboorde werktuigen en hamerbijlen.',
    pitfall: 'Natuurlijke holtes, fossiele kanaaltjes of recente beschadiging zijn geen doorboring.',
    source: 'Algoritme vraag 2, handleiding doorboorde artefacten',
  },
  '3': {
    short: 'Bepaal eerst de steensoort grofweg: vuursteen, kwartsiet en lydiet volgen in de bron een andere route dan andere steensoorten.',
    detail: 'Veel kern-, kling- en bifaciale typologie in het algoritme is specifiek voor deze groep gesteenten.',
    pitfall: 'Sterk verweerde of gepatineerde stukken kunnen de steensoort minder duidelijk maken.',
    source: 'Algoritme vraag 3, handleiding materiaalkeuze',
  },
  '5': {
    short: 'Kijk alleen naar echt gladde, gepolijste vlakken; gewone breukvlakken tellen niet als geslepen.',
    detail: 'Geslepen vuursteen heeft een bewust afgewerkt oppervlak. Ruwe breukvlakken blijven korrelig of schelpvormig.',
    pitfall: 'Verwar glans door gebruik of verwering niet met een werkelijk geslepen vlak.',
    source: 'Algoritme vraag 5, handleiding geslepen artefacten',
  },
  '6': {
    short: 'Een ventrale zijde is de gladde buikzijde van een afslag of kling, vaak met een slagbult.',
    detail: 'Zo’n ventrale zijde wijst erop dat je met een afslag of kling te maken hebt, niet met een kern of bifaciaal werktuig.',
    pitfall: 'Kijk niet alleen naar gladheid; zoek ook naar slagpunt en afslagvolgorde.',
    source: 'Algoritme vraag 6, handleiding basiskenmerken afslag/kling',
  },
  '7': {
    short: 'Afslagnegatieven zijn littekens van eerder afgeslagen stukken, geen toevallige kras of recente breuk.',
    detail: 'Let op holle negatieven met duidelijke richting en samenhang in het reductiepatroon.',
    pitfall: 'Recente beschadigingen geven vaak losse, scherpe breuken zonder logisch patroon.',
    source: 'Algoritme vraag 7, handleiding basisdeterminatie',
  },
  '11': {
    short: 'Zoek naar een echt herkenbaar slagvlak waarop doelgericht is geslagen.',
    detail: 'Een groot of herkenbaar slagvlak opent in de bron de kernroutes met Levallois-, discus- of andere kernsubtypen.',
    pitfall: 'Een willekeurig breukvlak is nog geen slagvlak.',
    source: 'Algoritme vraag 11, handleiding kernkenmerken',
  },
  '12': {
    short: 'Levallois herken je aan naar het midden gerichte negatieven en een schildpadachtige opbouw.',
    detail: 'De afslagen zijn aan één zijde steiler; de kern oogt voorbereid om een gewenste afslag of kling te leveren.',
    pitfall: 'Een kern met alleen veel negatieven is niet automatisch Levallois.',
    source: 'Algoritme vraag 12, handleiding Levallois-techniek',
  },
  '12a': {
    short: 'Een discusvormige kern heeft rondom naar het midden gerichte negatieven aan beide zijden.',
    detail: 'De vorm is rond of schijfachtig, met reductie aan boven- en onderzijde.',
    pitfall: 'Verwar een enkele bolle zijde niet met een echte discusvormige opbouw.',
    source: 'Algoritme vraag 12a, handleiding diskusvormige kernen',
  },
  '13': {
    short: 'Een gelegenheidskern heeft slechts enkele vrij toevallige afslagnegatieven en weinig systematische voorbereiding.',
    detail: 'De bron gebruikt deze vraag om eenvoudige ad-hoc kernen af te scheiden van duidelijker georganiseerde kernsubtypen.',
    pitfall: 'Twee of drie negatieven kunnen al doelgericht lijken; kijk naar samenhang en patroon.',
    source: 'Algoritme vraag 13, handleiding gelegenheidskernen',
  },
  '14': {
    short: 'Een Kombewa-kern of -afbouw toont één groot dominant afslagnegatief op een relatief massieve kern.',
    detail: 'De bron gebruikt deze vraag om zulke grote enkelnegatief-kernen van andere massieve kernvormen te scheiden.',
    pitfall: 'Een kern met meerdere bijna even grote negatieven past minder goed bij deze route.',
    source: 'Algoritme vraag 14, handleiding Kombewa-kernen',
  },
  '15': {
    short: 'Quina-kernen hebben twee net niet haaks op elkaar staande slagvlakken die om beurten worden gebruikt.',
    detail: 'Daarmee ontstaat een kenmerkende wisselende reductie in twee richtingen.',
    pitfall: 'Twee willekeurige breukvlakken zijn nog geen echte Quina-opbouw.',
    source: 'Algoritme vraag 15, handleiding Quina-kernen',
  },
  '20': {
    short: 'Zoek op de Levallois-kern naar één groot ovaal negatief van een doelafslag.',
    detail: 'Dat grote centrale negatief is kenmerkend voor de afslagvariant binnen Levallois.',
    pitfall: 'Meerdere losse negatieven zonder dominante afslag passen minder goed.',
    source: 'Algoritme vraag 20, handleiding Levallois-kernsubtypen',
  },
  '21': {
    short: 'Klingvormige negatieven op de Levallois-kern wijzen op een Levallois-klingkern.',
    detail: 'De negatieven zijn langwerpig en doelgericht voorbereid, niet enkel toevallig lang.',
    pitfall: 'Een gewone klingkern is niet hetzelfde als een Levallois-klingkern.',
    source: 'Algoritme vraag 21, handleiding Levallois-kernsubtypen',
  },
  '23': {
    short: 'Kijk of de naar het midden gerichte negatieven vooral aan één zijde of aan beide zijden liggen.',
    detail: 'Aan één zijde past bij herhaald gebruikte Levallois, aan beide zijden bij een diskusvormige kern.',
    pitfall: 'Laat je niet misleiden door een enkele bijkomende afslag aan de tweede zijde.',
    source: 'Algoritme vraag 23, handleiding Levallois versus diskusvorm',
  },
  '24': {
    short: 'Tel het aantal echte slagvlakken: één, twee of meer bepaalt direct het kernsubtype.',
    detail: 'De bron onderscheidt hier eenvoudige éénslagvlakkernen van meer complexe meerslagvlak-kernen.',
    pitfall: 'Een beschadigd randje of breukvlak is niet automatisch een functioneel slagvlak.',
    source: 'Algoritme vraag 24, handleiding kernslagvlakken',
  },
  '25': {
    short: 'Een piramidale afslagkern heeft rondom korte afslagnegatieven vanaf een relatief centraal slagvlak.',
    detail: 'Ontbreekt dat patroon en zijn de negatieven langer, dan ga je richting lamelle- of klingkern.',
    pitfall: 'Kijk naar het reductiepatroon rond de hele kern, niet alleen naar één zijde.',
    source: 'Algoritme vraag 25, handleiding afslag-, lamelle- en klingkernen',
  },
  '26': {
    short: 'Lamellekernen leveren zeer smalle, lange producten; bij bredere lange negatieven kom je uit bij klingkernen.',
    detail: 'De bron hanteert hier ongeveer 10 mm als praktische scheidslijn tussen lamelle en kling.',
    pitfall: 'Meet niet alleen één uitzonderlijk negatief; kijk naar het overheersende patroon op de kern.',
    source: 'Algoritme vraag 26, handleiding lamelle- versus klingkernen',
  },
  '27': {
    short: 'Een kielvormige kern heeft een duidelijk boot- of kielachtig profiel.',
    detail: 'Ontbreekt die bootvorm, dan blijf je in de gewone klingkernroute.',
    pitfall: 'Een licht bolle onderzijde maakt een kern nog niet meteen kielvormig.',
    source: 'Algoritme vraag 27, handleiding kielvormige kernen',
  },
  '27a': {
    short: 'De bron splitst grote klingkernen van kleinere varianten zoals Montbani-achtige routes.',
    detail: 'Formaat en robuustheid van de kern zijn hier bepalend, niet alleen de breedte van één negatief.',
    pitfall: 'Laat afbreuk of uitputting van de kern de oorspronkelijke grootte niet verhullen.',
    source: 'Algoritme vraag 27a, handleiding grote en kleine klingkernen',
  },
  '29': {
    short: 'Meer dan twee slagvlakken wijst op een complexere meerslagvlakkern.',
    detail: 'Bij precies twee slagvlakken vraagt de bron daarna door naar hun onderlinge positie.',
    pitfall: 'Verwar voorbereidende facetten of kleine inslagen niet met zelfstandige slagvlakken.',
    source: 'Algoritme vraag 29, handleiding meerslagvlakkernen',
  },
  '30': {
    short: 'Tegenover elkaar liggende slagvlakken geven een bidirectionele kern; anders eerder orthogonaal.',
    detail: 'Dit onderscheid zegt iets over de reductierichting en organisatie van de kern.',
    pitfall: 'Kijk naar de hoofdrichting van de negatieve littekens, niet alleen naar twee losse vlakjes.',
    source: 'Algoritme vraag 30, handleiding bidirectionele en orthogonale kernen',
  },
  '32': {
    short: 'Beoordeel of de brok, vorstsplijting of kern echt secundair als werktuig is gebruikt of bewerkt.',
    detail: 'De bron vraagt hier of je vanuit afval- of kernachtig materiaal alsnog naar een gemodificeerde werktuigroute moet doorschakelen.',
    pitfall: 'Losse recente stoten of wat randschade maken een brok nog niet “mogelijk gemodificeerd”.',
    source: 'Algoritme vraag 32, handleiding gemodificeerde brok, vorstsplijting of kern',
  },
  '9a': {
    short: 'Een geteste brok of vorstsplijting heeft slechts één of twee duidelijke afslagnegatieven.',
    detail: 'Meer systematische reductie brengt je terug naar kern- of werktuigroutes; hier gaat het om zeer beperkte testslagen.',
    pitfall: 'Verwar natuurlijke breuken of recente schade niet met echte testnegatieven.',
    source: 'Algoritme vraag 9a, handleiding geteste brok of vorstsplijting',
  },
  '40': {
    short: 'Deze hoofdvraag scheidt onbewerkte afslagen en klingen van stukken die na het losslaan doelgericht zijn nabewerkt.',
    detail: 'Vanaf hier opent de hele werktuigrichting met schrabbers, spitsen, boren, rugmessen en andere afslag- of klingwerktuigen.',
    pitfall: 'Gebruikssporen of toevallige randbeschadiging zijn niet automatisch bewuste nabewerking.',
    source: 'Algoritme vraag 40, handleiding afslag- en klingwerktuigen',
  },
  '41': {
    short: 'De lengte-breedteverhouding scheidt een afslag van een kling: klingen zijn duidelijk langer dan breed.',
    detail: 'Bij maximaal ongeveer twee keer de breedte blijf je in de afslaggroep; daarboven ga je naar de klinggroep.',
    pitfall: 'Een afgebroken kling kan kort lijken; beoordeel de oorspronkelijke vorm als die nog herkenbaar is.',
    source: 'Algoritme vraag 41, handleiding afslagen en klingen',
  },
  '71': {
    short: 'Cortex op de dorsale zijde wijst op een vroege kling of een natuurlijke rug.',
    detail: 'Controleer of de cortex echt op de rug ligt tegenover een scherpe zijde; dat kan richting rugmes wijzen.',
    pitfall: 'Restcortex alleen op een klein hoekje is minder overtuigend.',
    source: 'Algoritme vraag 71, handleiding klinggroepen',
  },
  '73': {
    short: 'Een Levallois-kling toont een voorbereid dorsaal patroon met naar het midden gerichte negatieven.',
    detail: 'Kijk naar regelmaat en voorbereiding, niet alleen naar langwerpigheid.',
    pitfall: 'Veel klingen zijn lang, maar missen het typische Levallois-patroon.',
    source: 'Algoritme vraag 73, handleiding Levallois-klingen',
  },
  '75': {
    short: 'Kernpreparatieklingen tonen op de dorsale zijde sporen die haaks staan op de uiteindelijke slagrichting.',
    detail: 'Ze zijn gemaakt om de kern verder voor te bereiden, niet als eindproduct.',
    pitfall: 'Verwar dwarse preparatiesporen niet met latere retouche.',
    source: 'Algoritme vraag 75, handleiding kernpreparatieklingen',
  },
  '77': {
    short: 'Montbani-achtige klingen hebben regelmatige, parallelle zijden en negatieven.',
    detail: 'De kling oogt gestandaardiseerd en strak in plaats van grillig of toevallig.',
    pitfall: 'Niet elke rechte kling is meteen Montbani-stijl.',
    source: 'Algoritme vraag 77, handleiding klingsubtypen',
  },
  '85': {
    short: 'Vraag je af of er na het losslaan nog bewuste nabewerking is aangebracht.',
    detail: 'Bij gemodificeerde klingen gaat het om retouche of een duidelijk gevormde werkrand.',
    pitfall: 'Gebruikssporen of kleine beschadigingen zijn niet altijd bewuste modificatie.',
    source: 'Algoritme vraag 85, handleiding gemodificeerde klingen',
  },
  '101': {
    short: 'Versplinterde uiteinden horen bij verbrijzelde of zwaar belaste werktuigen.',
    detail: 'Kijk naar duidelijke uiteinden met samengedrukte of versplinterde randen, niet naar gewone chips.',
    pitfall: 'Recente schade kan hierop lijken, maar mist vaak systematiek.',
    source: 'Algoritme vraag 101, handleiding verbrijzelde artefacten',
  },
  '102': {
    short: 'Gekerfd of getand betekent dat de rand doelgericht inkepingen of een zaagtandig patroon heeft.',
    detail: 'Dit opent in de bron de gekerfde en getande werktuiggroepen als aparte richting binnen grof bewerkte artefacten.',
    pitfall: 'Onregelmatige gebruiksschade of postdepositionele chips geven vaak geen consequent patroon.',
    source: 'Algoritme vraag 102, handleiding gekerfde en getande werktuigen',
  },
  '103': {
    short: 'Fijn bewerkt met oppervlakteretouche betekent systematische, relatief fijne retouche over het oppervlak.',
    detail: 'Dat opent in de bron de fijn bewerkte bifaciale en dolk/spits-routes.',
    pitfall: 'Grove bekapping of enkele grote afslagen tellen hier niet als fijne oppervlakteretouche.',
    source: 'Algoritme vraag 103, handleiding fijn versus grof bifaciaal',
  },
  '104': {
    short: 'Kijk of alleen een klein deel doelgericht bekapt is, of dat een groter deel van het artefact is vormgegeven.',
    detail: 'Die knip stuurt in de bron naar eenvoudige kleine kernwerktuigen versus verder uitgewerkte grof bewerkte typen.',
    pitfall: 'Een enkele beschadigde hoek is nog geen bewust “klein deel bekapt”.',
    source: 'Algoritme vraag 104, handleiding grof bewerkte artefacten',
  },
  '110': {
    short: 'Beoordeel eerst de globale vorm: bijl, vuistbijl, bladvorm of iets anders bifaciaals.',
    detail: 'Deze stap bepaalt of je naar vuistbijlen en bladvormen gaat of naar andere bifaciale werktuigen.',
    pitfall: 'Laat je niet alleen leiden door één punt of één snede; kijk naar de totale contour.',
    source: 'Algoritme vraag 110, handleiding bifaciale hoofdgroepen',
  },
  '125': {
    short: 'Een afgewerkte werkkant of punt wijst op vuistbijl- of bladvormroutes; een echte snede eerder op bijl/beitel.',
    detail: 'Dit is de hoofdknip tussen vuistbijlvormen en kernwerktuigen met snede.',
    pitfall: 'Een beschadigde punt kan ten onrechte op een snede lijken.',
    source: 'Algoritme vraag 125, handleiding vuistbijl versus bijl/beitel',
  },
  '126': {
    short: 'Vraag hier of de werkende kant echt als snede is vormgegeven, niet alleen als punt of stompe rand.',
    detail: 'Een echte snede opent in de bron de bijl-, beitel- en kernwerktuigroutes; zonder snede ga je naar vuistbijl of bladvorm.',
    pitfall: 'Een afgebroken of afgeronde rand kan op een snede lijken terwijl het oorspronkelijk een puntvorm was.',
    source: 'Algoritme vraag 126, handleiding bijl, beitel versus vuistbijlvorm',
  },
  '130': {
    short: 'Een uniface is maar aan één vlak duidelijk bewerkt, of bestaat uit een afslag met enkelzijdige vormgeving.',
    detail: 'Tweezijdige bewerking brengt je verder in de echte vuistbijl- en bladvormgroep.',
    pitfall: 'Een vlakke natuurlijke zijde is niet hetzelfde als bewust eenzijdig bewerken.',
    source: 'Algoritme vraag 130, handleiding unifaces en bifaciale werktuigen',
  },
  '131': {
    short: 'Relatief dun en plat wijst op bladvormen; dikkere stukken horen eerder bij vuistbijlen.',
    detail: 'De bron gebruikt deze knip om dunne bladachtige vormen los te trekken van robuustere vuistbijlen.',
    pitfall: 'Laat plaatselijke dikte door breuk of beschadiging de globale indruk niet overheersen.',
    source: 'Algoritme vraag 131, handleiding bladvormen versus vuistbijlen',
  },
  '132': {
    short: 'Een proto-vuistbijl oogt primitief en staat qua vorm tussen chopping tool en echte vuistbijl in.',
    detail: 'De bewerking is minder uitgewerkt dan bij een volwaardige vuistbijl, maar duidelijk verder dan een gewone chopping tool.',
    pitfall: 'Een grof of beschadigd werktuig is niet automatisch een proto-vuistbijl.',
    source: 'Algoritme vraag 132, handleiding proto-vuistbijlen',
  },
  '133': {
    short: 'Langwerpig met vrij rechte zijden wijst in de bron naar lancetvormige vuistbijlen.',
    detail: 'Als de zijden niet recht genoeg zijn, volgt de boom verder naar andere langwerpige of hartvormige subtypen.',
    pitfall: 'Een smalle amandelvorm kan op het eerste oog te recht lijken; kijk naar de hele contour.',
    source: 'Algoritme vraag 133, handleiding lancetvormige vuistbijlen',
  },
  '135': {
    short: 'Een Micoque-vuistbijl is langwerpig, heeft concave zijden en is fijner bewerkt dan ficron of lancetvormig.',
    detail: 'De bron gebruikt vooral de combinatie van slanke vorm, concave zijden en zorgvuldiger afwerking.',
    pitfall: 'Laat je niet alleen leiden door lengte; de concave zijden en afwerkingsgraad zijn hier cruciaal.',
    source: 'Algoritme vraag 135, handleiding Micoque-vuistbijlen',
  },
  '135a': {
    short: 'Een amandelvormige vuistbijl heeft een ronde, vrij onduidelijke punt en een gelijkmatig ovale contour.',
    detail: 'Past die indruk niet, dan loopt de bron verder naar flesvormige vuistbijlen.',
    pitfall: 'Een afgesleten punt kan een ander subtype ten onrechte amandelvormig laten lijken.',
    source: 'Algoritme vraag 135a, handleiding amandel- en flesvormige vuistbijlen',
  },
  '146': {
    short: 'Een Fäustel is een kleine vuistbijl, doorgaans kleiner dan ongeveer 6 cm.',
    detail: 'De bron gebruikt formaat hier expliciet om deze kleine vuistbijlvorm af te scheiden van grotere typen.',
    pitfall: 'Meet het complete artefact; een afgebroken groter stuk kan ten onrechte klein lijken.',
    source: 'Algoritme vraag 146, handleiding Fäustel',
  },
  '136': {
    short: 'Hier splitst de bron dunnere vuistbijlen van heel kleine of heel dunne vormen.',
    detail: 'Dunnere vuistbijlen gaan daarna naar driehoekige en hartvormige subtypen.',
    pitfall: 'Gebruik breedte-dikteverhouding en totale indruk samen, niet alleen op het oog.',
    source: 'Algoritme vraag 136, handleiding vuistbijlsubtypen',
  },
  '137': {
    short: 'Een driehoekige vuistbijl heeft rechte tot licht convexe of concave zijden en een rechte, scherpe basis.',
    detail: 'Past hij net niet zuiver, dan gaat de bron verder naar langwerpig of sub-driehoekig.',
    pitfall: 'Verwar driehoekige vuistbijlen niet met smalle lancetvormen of bout-coupé.',
    source: 'Algoritme vraag 137, handleiding driehoekige vuistbijlen',
  },
  '333': {
    short: 'Controleer of de schrabber echt op een kling is gemaakt en niet op een afslag.',
    detail: 'Een klingbasis is langwerpig en relatief smal; daarna splitst de bron verder naar klingschrabber-subtypen.',
    pitfall: 'Een brede kling kan op een afslag lijken als je alleen naar de kap kijkt.',
    source: 'Algoritme vraag 333, handleiding schrabbers op kling',
  },
  '335': {
    short: 'Een schrabberkap aan één uiteinde wijst op een enkelvoudige klingschrabber.',
    detail: 'Zit er ook een tweede actieve kap aan het andere uiteinde, dan hoort hij in de dubbele subtypegroep.',
    pitfall: 'Een beschadigd uiteinde is niet automatisch een tweede schrabberkap.',
    source: 'Algoritme vraag 335, handleiding klingschrabbers',
  },
  '201': {
    short: 'Bekapt betekent hier dat de afslag of kling niet echt geretoucheerd is, maar wel een steil afgeknot of afgekapt uiteinde heeft.',
    detail: 'Ontbreekt die bekapping, dan ga je in de bron door naar retouche of bijzondere bewerking.',
    pitfall: 'Een toevallig afgebroken uiteinde is niet automatisch bewuste bekapping.',
    source: 'Algoritme vraag 201, handleiding bekapte artefacten',
  },
  '202': {
    short: 'Zoek naar een kleine beitelkant of een negatief van een stekerafslag aan het uiteinde of de rand.',
    detail: 'Dat opent de stekergroep binnen de afslag- en klingwerktuigen.',
    pitfall: 'Een scherp hoekje door breuk is nog geen steker.',
    source: 'Algoritme vraag 202, handleiding stekers',
  },
  '203': {
    short: 'Vraag hier of de steker op een ander werktuigtype is aangebracht, dus deel is van een combinatiewerktuig.',
    detail: 'Dan hoort het stuk in de combinatiegroep, niet bij de enkelvoudige stekers.',
    pitfall: 'Een steker op een retoucheerde kling is niet automatisch een duidelijk combinatiewerktuig; kijk naar beide werktuigfuncties.',
    source: 'Algoritme vraag 203, handleiding combinatiewerktuigen met steker',
  },
  '204': {
    short: 'Meervoudige stekers hebben meerdere kleine beitelkanten of meerdere stekerafslagen.',
    detail: 'Die meerdere actieve uiteinden onderscheiden ze van enkelvoudige stekers.',
    pitfall: 'Secundaire schade naast één echte beitelkant maakt een steker niet meteen meervoudig.',
    source: 'Algoritme vraag 204, handleiding meervoudige stekers',
  },
  '205': {
    short: 'Een beksteker is bekvormig en vaak met mini-stekerafslagen van ventraal naar dorsaal gevormd.',
    detail: 'De “bek” springt als puntige uitstulping naar voren.',
    pitfall: 'Een gewone stekerhoek zonder duidelijke bekvorm past minder goed bij dit subtype.',
    source: 'Algoritme vraag 205, handleiding bekstekers',
  },
  '207': {
    short: 'Hier zoek je naar een alternerend gevormde beitelkant, deels dorsaal en deels ventraal, onder hoek op het vlak van het stuk.',
    detail: 'Dat geeft een specifieke alternerende bek- of RR-stekervorm.',
    pitfall: 'Eenzijdige retouche of een gewone stekerafslag is iets anders dan zo’n alternerende opbouw.',
    source: 'Algoritme vraag 207, handleiding alternerende stekers',
  },
  '209': {
    short: 'Een kerfrest of microsteker ontstaat via een opzettelijk getordeerde breuk met zichtbaar spoor van een geretoucheerde kerf.',
    detail: 'De bron scheidt dit van gewone stekers die echt door stekerafslag zijn gemaakt.',
    pitfall: 'Niet elke torsiebreuk of kleine splinter is een microsteker.',
    source: 'Algoritme vraag 209, handleiding kerfrest en microsteker',
  },
  '210': {
    short: 'Een A-steker is met één enkele stekerafslag gemaakt, zonder voorbereiding van het slagvlak.',
    detail: 'De eenvoud van de afslagtechniek is hier het onderscheidende kenmerk.',
    pitfall: 'Een ogenschijnlijk enkele afslag kan toch vooraf zijn voorbereid; kijk naar het slagvlak.',
    source: 'Algoritme vraag 210, handleiding A-stekers',
  },
  '211': {
    short: 'Bij een Corbiac-steker is de stekerafslag zijwaarts, dus haaks op de slagrichting van afslag of kling, aangebracht.',
    detail: 'Die transversale oriëntatie is hier doorslaggevend.',
    pitfall: 'Een gewone eindsteker met lichte scheefstand is nog geen Corbiac-vorm.',
    source: 'Algoritme vraag 211, handleiding Corbiac-stekers',
  },
  '213': {
    short: 'Een RA-steker met zijwaartse stekerafslag valt in de transversale stekergroep.',
    detail: 'De richting van de stekerafslag ten opzichte van het basisstuk is hier beslissend.',
    pitfall: 'Kijk naar de werkelijke afslagbaan, niet alleen naar de stand van de beitelkant.',
    source: 'Algoritme vraag 213, handleiding transversale stekers',
  },
  '300': {
    short: 'Een afgeknot artefact heeft op het uiteinde een vrij steile retouche, vaak schuin ten opzichte van de lengteas.',
    detail: 'Die bekapping zit meestal distaal en vormt een duidelijk afgevlakt of schuin afgesneden uiteinde.',
    pitfall: 'Een recht afgebroken top zonder retouche telt niet als echte afknotting.',
    source: 'Algoritme vraag 300, handleiding afgeknotte artefacten',
  },
  '320': {
    short: 'Een schrabber heeft een relatief steil geretoucheerde, vaak gebogen werkkant, soms bijna rondom.',
    detail: 'Vanaf hier splitst de bron verder naar dunne, ronde, micro-, snuit- en andere schrabbertypen.',
    pitfall: 'Een korte steile retouche op één punt maakt een stuk nog niet meteen tot schrabber.',
    source: 'Algoritme vraag 320, handleiding schrabbers',
  },
  '321': {
    short: 'Een dunne schrabber heeft lichte retouche en zit vaak als onderdeel in een combinatiewerktuig.',
    detail: 'De schrabberkap is dan minder massief dan bij gewone schrabbers.',
    pitfall: 'Laat een smal retoucheboogje niet te snel als “dunne schrabber” tellen zonder duidelijke kap.',
    source: 'Algoritme vraag 321, handleiding dunne schrabbers',
  },
  '323': {
    short: 'Een grote ronde of ovale schrabber is fors en vrijwel rondom geretoucheerd.',
    detail: 'De contour en omtrekretouche zijn hier bepalend, meer dan één afzonderlijke kap.',
    pitfall: 'Een afgeronde afslag met retouche op één zijde is nog geen grote ronde schrabber.',
    source: 'Algoritme vraag 323, handleiding ronde en ovale schrabbers',
  },
  '324': {
    short: 'Micro- of knoopschrabbers zijn erg klein; de bron legt de grens hier bij ongeveer 18 mm.',
    detail: 'Dat maakt formaat zelf een kernkenmerk van het subtype.',
    pitfall: 'Meet het complete artefact en niet alleen de schrabberkap.',
    source: 'Algoritme vraag 324, handleiding micro- en knoopschrabbers',
  },
  '326': {
    short: 'Een snuitschrabber heeft een smalle, relatief dikke schrabberkap die als “snuit” uitsteekt.',
    detail: 'De actieve kap is meestal duidelijk smaller dan de rest van het stuk.',
    pitfall: 'Een beschadigde punt of gewone smalle retouche maakt nog geen snuitschrabber.',
    source: 'Algoritme vraag 326, handleiding snuitschrabbers',
  },
  '350': {
    short: 'Een limace is zeer dik en heeft twee ongeveer steil geretoucheerde lange zijden.',
    detail: 'Dit is een robuuste schaafvorm die zich duidelijk onderscheidt van gewone schrabbers of schaven op dunnere afslagen.',
    pitfall: 'Een dik stuk met alleen aan één zijde retouche past minder goed bij limace.',
    source: 'Algoritme vraag 350, handleiding limace en dikke schaven',
  },
  '351': {
    short: 'Een schaaf heeft op een vrij grove afslag een doorlopende vlakke of schubvormig geretoucheerde werkkant.',
    detail: 'De retouche vormt hier een samenhangende, min of meer scherpe actieve rand.',
    pitfall: 'Losse inkepingen of stukjes retouche zonder doorlopende werkrand maken nog geen echte schaaf.',
    source: 'Algoritme vraag 351, handleiding schaven',
  },
  '380': {
    short: 'Een rugmes heeft een driehoekige dwarsdoorsnede met één scherpe ongeretoucheerde rand tegenover een dikke rug.',
    detail: 'Die rug kan natuurlijk, corticaal of door steile retouche gevormd zijn, zolang de scherpe rand er duidelijk tegenover ligt.',
    pitfall: 'Een gewone kling met één retoucheerde zijde is nog niet automatisch een rugmes.',
    source: 'Algoritme vraag 380, handleiding rugmessen',
  },
  '390': {
    short: 'Hier scheidt de bron steil geretoucheerde werktuigen van vlakke rand- of oppervlakteretouche.',
    detail: 'Dat is een hoofdknip tussen schrabber/spitsachtige groepen en de fijnere oppervlakteretouche-routes.',
    pitfall: 'Kijk naar retouchehoek en algemeen profiel, niet alleen naar het aantal geretoucheerde randen.',
    source: 'Algoritme vraag 390, handleiding steile versus vlakke retouche',
  },
  '391': {
    short: 'Beoordeel eerst of het artefact echt een duidelijke punt of juist een geometrische vorm heeft.',
    detail: 'Deze stap opent daarna de spitsroutes versus de geometrische groepen.',
    pitfall: 'Een afgebroken hoek kan op een punt lijken zonder dat de vorm als spits bedoeld was.',
    source: 'Algoritme vraag 391, handleiding spitsen en geometrische vormen',
  },
  '410': {
    short: 'Gesteelde spitsen en spitsen met gekerfde basis vormen in de bron een eigen hoofdgroep.',
    detail: 'Een steel of uitgesproken basisinkeping leidt daarna naar steelspitsen, gekerfde en weerhaakvormen.',
    pitfall: 'Een versmalde of beschadigde basis is nog geen echte steel of kerf.',
    source: 'Algoritme vraag 410, handleiding gesteelde spitsen',
  },
  '412': {
    short: 'Kijk of de spits maar aan één zijde een kerf heeft of symmetrisch aan beide zijden is ingesneden.',
    detail: 'Die basisindeling stuurt in de bron naar verschillende steel- en basisvormige spitsgroepen.',
    pitfall: 'Een ondiepe beschadiging aan de andere zijde is nog geen echte tweede kerf.',
    source: 'Algoritme vraag 412, handleiding gekerfde en gesteelde spitsen',
  },
  '413': {
    short: 'De Ahrensburg/Hintersee-vorm is relatief kort en krijgt door twee geretoucheerde kerven een duidelijke steel.',
    detail: 'De punt zelf ontstaat uit een aan één zijde geretoucheerde kling.',
    pitfall: 'Niet elke gesteelde spits met twee inkepingen is automatisch Ahrensburg/Hintersee; let ook op formaat en opbouw.',
    source: 'Algoritme vraag 413, handleiding Ahrensburg- en Hintersee-spitsen',
  },
  '414': {
    short: 'Een Havelter-steelspits is relatief lang en heeft een korte steel door twee ongelijke kerven.',
    detail: 'De retouche kan aan de steel zelfs asymmetrisch over dorsale en ventrale zijde verlopen.',
    pitfall: 'Kijk echt naar ongelijke kerven en steelvorming; een gewone gesteelde spits is nog geen Havelter-type.',
    source: 'Algoritme vraag 414, handleiding Havelter-steelspitsen',
  },
  '451': {
    short: 'Een rechthoekig trapezium of vierhoek heeft één duidelijk haakse zijde.',
    detail: 'Deze vraag opent de rechthoekige vierhoek- en trapeziumtypen binnen de geometrische spitsen.',
    pitfall: 'Een bijna-haakse zijde door breuk is niet genoeg; de vorm moet als geheel kloppen.',
    source: 'Algoritme vraag 451, handleiding vierhoekige geometrische spitsen',
  },
  '452': {
    short: 'Een rombische vierhoek heeft een scheef ruitvormig profiel in plaats van een echt rechthoekige vorm.',
    detail: 'In de bron leidt dit naar Zonhoven-achtige en verwante vierhoekige spitsen.',
    pitfall: 'Een asymmetrisch trapezium is niet automatisch rombisch.',
    source: 'Algoritme vraag 452, handleiding rombische vierhoekige spitsen',
  },
  '454': {
    short: 'Bij een transversale spits is de lengte-breedteverhouding kleiner dan 1 wanneer je ongeretoucheerde en geretoucheerde zijde vergelijkt.',
    detail: 'De spits werkt dan als een dwarsgerichte snede of punt over de breedte van het stuk.',
    pitfall: 'Meet consequent volgens de bronoriëntatie; anders lijkt een trapezium snel transversaal.',
    source: 'Algoritme vraag 454, handleiding transversale spitsen',
  },
  '470': {
    short: 'Een cirkelsegmentvormige dubbelspits heeft twee punten en een duidelijke segmentvorm.',
    detail: 'Daarna vraagt de bron door naar Azilien, cirkelsegment en andere segmentvormige spitsen.',
    pitfall: 'Een gewone gebogen spits is nog geen echte cirkelsegmentvorm.',
    source: 'Algoritme vraag 470, handleiding segmentvormige spitsen',
  },
  '476': {
    short: 'Kijk of één zijde volledig of gedeeltelijk geretoucheerd is, eventueel met een geretoucheerde basis.',
    detail: 'Deze route opent veel eenzijdig geretoucheerde spitsen zoals Tjonger, Cheddar en Creswell.',
    pitfall: 'Gebruikssporen langs één zijde zijn niet hetzelfde als systematische retouche.',
    source: 'Algoritme vraag 476, handleiding eenzijdig geretoucheerde spitsen',
  },
  '430': {
    short: 'Bepaal eerst of de spits geometrisch is: driehoek, vierhoek of segmentvormig.',
    detail: 'Deze hoofdvraag opent de geometrische spitsroutes binnen de AWN-boom.',
    pitfall: 'Een gewone spits met wat rechte zijden is nog niet automatisch een geometrische vorm.',
    source: 'Algoritme vraag 430, handleiding geometrische spitsen',
  },
  '431': {
    short: 'Kijk of de contour echt driehoekig is en niet eerder trapezium- of vierhoekig.',
    detail: 'Driehoekige geometrische spitsen worden daarna verder uitgesplitst naar micro-, gelijkbenige en ongelijkbenige vormen.',
    pitfall: 'Een afgebroken basis kan een vierhoek of trapezium ten onrechte driehoekig laten lijken.',
    source: 'Algoritme vraag 431, handleiding driehoekige geometrische spitsen',
  },
  '450': {
    short: 'Vierhoekige vormen en transversalen worden in de bron los van driehoeken en segmenten uitgewerkt.',
    detail: 'Deze vraag opent de vierhoekige, trapezium- en transversaalroutes.',
    pitfall: 'Let op of de breedte- en basisverhoudingen niet beter bij een trapezium passen.',
    source: 'Algoritme vraag 450, handleiding vierhoekige en trapeziumvormige spitsen',
  },
  '477': {
    short: 'Bepaal of één zijde volledig geretoucheerd is of maar gedeeltelijk.',
    detail: 'Dat onderscheid is essentieel voor Tjonger-, Cheddar-, Creswell- en verwante spitsen.',
    pitfall: 'Een lange beschadiging langs de rand is niet per se volledige retouche.',
    source: 'Algoritme vraag 477, handleiding eenzijdig geretoucheerde spitsen',
  },
  '478': {
    short: 'Controleer of de basis ongeretoucheerd is of juist mee in de retouche is opgenomen.',
    detail: 'Hiermee splitst de bron de klassieke B-spitsen van andere eenzijdig geretoucheerde vormen.',
    pitfall: 'Een klein bijgewerkt hoekje telt nog niet als echt geretoucheerde basis.',
    source: 'Algoritme vraag 478, handleiding eenzijdig geretoucheerde spitsen',
  },
  '479': {
    short: 'Een gedeeltelijk geretoucheerde zijde met schuin afgeknotte indruk opent de Tjonger/Cheddar/Creswell-groep.',
    detail: 'Dit zijn slanke spitsen waarbij de retouche niet de hele zijde bestrijkt.',
    pitfall: 'Kijk of de afknotting echt intentioneel en steil is, niet alleen afgebroken.',
    source: 'Algoritme vraag 479, handleiding Tjonger- en verwante spitsen',
  },
  '493': {
    short: 'Zoek naar een slanke spits met nagenoeg evenwijdige zijden en gekruiste steile retouche.',
    detail: 'Deze vraag scheidt Gravette/Blanchère van de meer lamellaire en naaldvormige typen.',
    pitfall: 'Een smalle spits zonder gekruiste retouche past hier minder goed.',
    source: 'Algoritme vraag 493, handleiding slanke steil geretoucheerde spitsen',
  },
  '495': {
    short: 'Een Sauveterre-spits is een kleine lamelle, tweezijdig geretoucheerd, met twee scherpe uiteinden.',
    detail: 'De verhouding lengte-breedte is hier van belang; de bron noemt L:B groter dan 4.',
    pitfall: 'Niet elke retoucheerde lamelle is automatisch Sauveterre.',
    source: 'Algoritme vraag 495, handleiding Sauveterre-spitsen',
  },
  '496': {
    short: 'Let op een min of meer driehoekige vorm met één geheel en één gedeeltelijk van de top geretoucheerde zijde.',
    detail: 'Dit is de D-spits-route binnen de eenzijdig/tweezijdig geretoucheerde slanke spitsen.',
    pitfall: 'Een te brede of te symmetrische spits past minder goed bij dit subtype.',
    source: 'Algoritme vraag 496, handleiding D-spitsen',
  },
  '497': {
    short: 'Een naaldvormige spits is smal, lang en aan beide zijden geretoucheerd, met één duidelijke punt.',
    detail: 'De bron vraagt hier ook om een hoge lengte-breedteverhouding.',
    pitfall: 'Verwar dit niet met een tweepuntige lamelle of Sauveterre-vorm.',
    source: 'Algoritme vraag 497, handleiding naaldvormige spitsen',
  },
  '600': {
    short: 'Vraag eerst of het geslepen artefact uit een bijlfragment is gemaakt; dat is een aparte groep.',
    detail: 'Een gepolijst fragment met secundaire vormgeving kan hier thuishoren.',
    pitfall: 'Niet elk fragment met een glad vlak is automatisch van een bijl afkomstig.',
    source: 'Algoritme vraag 600, handleiding geslepen vuurstenen artefacten',
  },
  '601': {
    short: 'Beoordeel of het geslepen artefact echt de globale vorm van een bijl of beitel heeft.',
    detail: 'Dat onderscheidt de bijl- en beitelroutes van andere geslepen vuurstenen artefacten zoals fragmenten, dolken of hergebruikte stukken.',
    pitfall: 'Een afgebroken fragment kan door één bewaard uiteinde ten onrechte op een bijl lijken.',
    source: 'Algoritme vraag 601, handleiding geslepen vuurstenen artefacten',
  },
  '602': {
    short: 'De breedteknip rond 2,9 cm scheidt bijlen van smallere beitels in de bron.',
    detail: 'Breder wijst richting bijl, smaller richting beitel en guts/disselbeitel.',
    pitfall: 'Meet op het breedste punt van het werktuig en niet alleen bij de snede.',
    source: 'Algoritme vraag 602, handleiding geslepen bijlen en beitels',
  },
  '603': {
    short: 'Een dissel heeft de snede niet centraal maar uit het midden, waardoor hij asymmetrisch werkt.',
    detail: 'Bij andere steensoorten gebruikt de bron dit als hoofdknip tussen gewone bijlen en dissels.',
    pitfall: 'Een beschadigde of schuin afgesleten snede is niet automatisch een echte disselvorm.',
    source: 'Algoritme vraag 603, handleiding dissels en bijlen van andere steensoorten',
  },
  '604': {
    short: 'De bron splitst hier vuursteen en lydiet van andere steensoorten omdat de verdere bijltypologie anders loopt.',
    detail: 'Vuursteen en lydiet volgen in de app de uitgewerkte vuursteenroute; andere steensoorten gaan naar een aparte tak.',
    pitfall: 'Donkere patina of verwering kan een andere steensoort te snel op lydiet laten lijken.',
    source: 'Algoritme vraag 604, handleiding geslepen bijlen naar steensoort',
  },
  '606': {
    short: 'Een klokvormige vlakbijl heeft gebogen zijden en zijn grootste breedte ongeveer op een derde vanaf de snede.',
    detail: 'Dat geeft de typische “klok”-contour binnen de vlakbijlsubtypen.',
    pitfall: 'Een gewone waaiervorm of afgeronde bijl is nog niet automatisch klokvormig.',
    source: 'Algoritme vraag 606, handleiding klokvormige vlakbijlen',
  },
  '640': {
    short: 'Bij beitels is de breedte ongeveer gelijk aan de dikte; bredere stukken lopen eerder als bijlroute.',
    detail: 'De bron gebruikt hier opnieuw een vorm- en maatverhouding om beitels te scheiden van bijlen.',
    pitfall: 'Meet niet alleen bij de snede; het hele lichaam van het werktuig telt mee.',
    source: 'Algoritme vraag 640, handleiding beitels',
  },
  '700': {
    short: 'Kijk of het gat echt volledig door het artefact gaat.',
    detail: 'Volledig doorboord opent de rolsteen-, schijfsteen-, dubbelbijl- en hamerbijlroutes.',
    pitfall: 'Een begin van een boring of natuurlijke holte is nog geen volledig doorboord artefact.',
    source: 'Algoritme vraag 700, handleiding doorboorde artefacten',
  },
  '711': {
    short: 'Een hamervorm opent de hamerbijlgroep; anders blijf je in andere doorboorde werktuigtypen.',
    detail: 'Daarna volgt in de bron het onderscheid tussen gefacetteerde, knop- en andere hamerbijlen.',
    pitfall: 'Een dubbelbijl of schoenleestwig kan globaal massief lijken, maar is niet automatisch hamervormig.',
    source: 'Algoritme vraag 711, handleiding hamerbijlen',
  },
  '137a': {
    short: 'Als de vuistbijl niet zuiver driehoekig is, kijk dan of hij langwerpig driehoekig of sub-driehoekig is.',
    detail: 'Dit zijn beide varianten binnen de driehoekige vuistbijlgroep.',
    pitfall: 'Een hartvormige indruk kan hier verwarrend zijn; vergelijk ook de basisvorm.',
    source: 'Algoritme vraag 137a, handleiding driehoekige vuistbijlen',
  },
  '138': {
    short: 'Een hartvormige vuistbijl heeft zeer convexe zijden, een ronde basis en een enigszins ronde punt.',
    detail: 'Past hij niet precies, dan gaat de bron verder naar langwerpig en sub-hartvormig.',
    pitfall: 'Verwar een brede amandelvorm niet met een echte hartvormige vuistbijl.',
    source: 'Algoritme vraag 138, handleiding hartvormige vuistbijlen',
  },
  '138a': {
    short: 'Hier splitst de bron langwerpig hartvormige en sub-hartvormige vuistbijlen.',
    detail: 'Het gaat om varianten die wel in de hartvormige familie vallen, maar minder klassiek ogen.',
    pitfall: 'Kijk naar de totale contour, niet alleen naar de punt.',
    source: 'Algoritme vraag 138a, handleiding hartvormige vuistbijlen',
  },
  '139': {
    short: 'Een bout-coupé is gedrongen, ogivaal-driehoekig en heeft convexe zijden met een enigszins convexe basis.',
    detail: 'Dit is een aparte korte, gedrongen subtypegroep binnen de vuistbijlen.',
    pitfall: 'Een beschadigde basis kan een bout-coupé onterecht overtuigend maken.',
    source: 'Algoritme vraag 139, handleiding bout-coupé',
  },
  '140': {
    short: 'Let op een korte snede, soms zelfs tranchetachtig, in plaats van een normale punt.',
    detail: 'Deze vraag opent de korte-snedegroepen voordat de ronde en ovale vormen volgen.',
    pitfall: 'Een afgeslagen punt is nog geen bewuste korte snede.',
    source: 'Algoritme vraag 140, handleiding vuistbijlen met korte snede',
  },
  '141': {
    short: 'Gedeeltelijk bewerkt, eenzijdig bewerkt of op dikke afslag gemaakt wijst op uniface.',
    detail: 'Hiermee onderscheidt de bron eenvoudige vuistbijlvormen van volledig uitgewerkte typen.',
    pitfall: 'Een slecht bewaarde vuistbijl is niet automatisch uniface.',
    source: 'Algoritme vraag 141, handleiding uniface',
  },
  '142': {
    short: 'Een limande is langgerekt ovaal: lengte duidelijk groter dan de breedte.',
    detail: 'De bron noemt hier een lengte-breedteverhouding groter dan ongeveer 1,5.',
    pitfall: 'Meet op de totale contour, niet alleen op het best bewaarde deel.',
    source: 'Algoritme vraag 142, handleiding limande',
  },
  '143': {
    short: 'Een ovale vuistbijl is compacter dan een limande en niet echt rond of bootvormig.',
    detail: 'Hier blijft de algemene ovale categorie over.',
    pitfall: 'Een bijna ronde vorm schuift eerder door naar de disque-groep.',
    source: 'Algoritme vraag 143, handleiding ovale vuistbijlen',
  },
  '144': {
    short: 'Een ronde/disque-vuistbijl heeft een echt ronde hoofdvorm met onduidelijke punt.',
    detail: 'Dit is een aparte compacte subtypegroep binnen de ronde vormen.',
    pitfall: 'Een versleten ovale vuistbijl kan ronder lijken dan hij oorspronkelijk was.',
    source: 'Algoritme vraag 144, handleiding ronde/disque-vuistbijlen',
  },
  '145': {
    short: 'Bootvormige vuistbijlen zijn ovaal tot vierhoekig en wijken af van de ronde en ovale typen.',
    detail: 'De contour is langgerekter en “bootachtig” in plaats van puur ovaal.',
    pitfall: 'Een asymmetrische bewaarvorm kan de bootvorm overdrijven.',
    source: 'Algoritme vraag 145, handleiding bootvormige vuistbijlen',
  },
  '701': {
    short: 'Een dikke, snedeloze doorboorde steen wijst op een rolsteen.',
    detail: 'De bron behandelt zulke massieve doorboorde objecten apart van bijl- en hamerbijlvormen.',
    pitfall: 'Een afgesleten snede kan een werktuig ten onrechte snedeloos laten lijken.',
    source: 'Algoritme vraag 701, handleiding doorboorde rolstenen',
  },
  '702': {
    short: 'Een plat of schijfvormig doorboord artefact hoort in de schijfvormige groep.',
    detail: 'Dit onderscheidt de platte doorboorde stenen van de massieve rolstenen.',
    pitfall: 'Een dun afgesleten rolsteenfragment kan schijfvormig lijken.',
    source: 'Algoritme vraag 702, handleiding doorboorde schijfstenen',
  },
  '703': {
    short: 'Kijk of de snede haaks op het gat staat; dat wijst op de schoenleest-bijlroute.',
    detail: 'Deze vraag scheidt werktuigen met dwarse snede van de langgerekte snede-evenwijdige typen.',
    pitfall: 'Let goed op de oorspronkelijke snederichting, niet op latere beschadiging.',
    source: 'Algoritme vraag 703, handleiding doorboorde bijlen en dissels',
  },
  '704': {
    short: 'Een snede evenwijdig aan het gat en niet in het midden wijst op de doorboorde schoenleestwig/disselgroep.',
    detail: 'Dit is een andere hoofdgroep dan de haaks gesneden schoenleest-bijl.',
    pitfall: 'Een asymmetrische slijtageplek is niet automatisch de oorspronkelijke snede.',
    source: 'Algoritme vraag 704, handleiding doorboorde schoenleestwiggen',
  },
  '705': {
    short: 'Een grof, breed wigvormig artefact met snede evenwijdig aan het gat past bij de doorboorde breedwig.',
    detail: 'Dit is een zware, meer wigvormige variant binnen de doorboorde werktuigen.',
    pitfall: 'Een fragment van een ander doorboord werktuig kan ten onrechte breedwigachtig lijken.',
    source: 'Algoritme vraag 705, handleiding doorboorde breedwiggen',
  },
  '706': {
    short: 'Een stompe punt in plaats van een brede snede opent de puntige hak-route.',
    detail: 'Hier scheidt de bron puntige hakken van snijdende doorboorde werktuigen.',
    pitfall: 'Een afgesleten of afgebroken snede kan op een stompe punt lijken.',
    source: 'Algoritme vraag 706, handleiding puntige hakken',
  },
  '707': {
    short: 'Een enigszins symmetrisch doorboord artefact met twee “snedes” opent de dubbelbijlroute.',
    detail: 'Daarna splitst de bron verder naar type A, B en C.',
    pitfall: 'Veel dubbelbijlen hebben in werkelijkheid maar één echte snede.',
    source: 'Algoritme vraag 707, handleiding dubbelbijlen',
  },
  '708': {
    short: 'Symmetrisch in zijaanzicht maar feitelijk één echte snede wijst op dubbelbijl type A.',
    detail: 'De positie van het gat ten opzichte van de stompe kant is hierbij bepalend.',
    pitfall: 'Een beschadigde tweede snede kan ten onrechte als type A overkomen.',
    source: 'Algoritme vraag 708, handleiding dubbelbijl type A',
  },
  '709': {
    short: 'Twee echte snedes wijzen op dubbelbijl type B.',
    detail: 'Als dat niet zo is, schuift de bron door naar de beitelvormige type C-route.',
    pitfall: 'Controleer of beide uiteinden echt als snede zijn gevormd.',
    source: 'Algoritme vraag 709, handleiding dubbelbijl type B',
  },
  '710': {
    short: 'Een beitelvorm met ovaal gat wijst op dubbelbijl type C.',
    detail: 'Dit is de beitelachtige dubbelbijlvariant binnen de bron.',
    pitfall: 'Verwar een asymmetrische hamerbijl niet met deze dubbelbijlvorm.',
    source: 'Algoritme vraag 710, handleiding dubbelbijl type C',
  },
  '712': {
    short: 'Gefacetteerde hamerbijlen vormen een aparte hoofdgroep binnen de hamerbijlen.',
    detail: 'Daarna splitst de bron ze verder uit in type 1, 2a en 2b.',
    pitfall: 'Slechte conservering kan facetvlakken minder zichtbaar maken.',
    source: 'Algoritme vraag 712, handleiding gefacetteerde hamerbijlen',
  },
  '716': {
    short: 'Een knopvormig uiteinde aan de nek wijst op een knop-hamerbijl.',
    detail: 'Ontbreekt die knop, dan loopt de bron door naar andere niet-gefacetteerde hamerbijlen.',
    pitfall: 'Een afgebroken nek kan een knopvorm maskeren.',
    source: 'Algoritme vraag 716, handleiding knop-hamerbijlen',
  },
  '717': {
    short: 'Convexe bovenzijde en concave onderzijde openen de grote vervolgboom van niet-gefacetteerde hamerbijlen.',
    detail: 'Daarna spelen doorsnede, verdikking en nekvorm een grote rol.',
    pitfall: 'Kijk naar het hele profiel, niet alleen naar een lokaal krom vlak.',
    source: 'Algoritme vraag 717, handleiding niet-gefacetteerde hamerbijlen',
  },
  '718': {
    short: 'Een sterke concave onderzijde en vierzijdige dwarsdoorsnede bij de nek wijzen op type H/G-routes.',
    detail: 'Hiermee scheidt de bron deze vormen van de K/L- en A/Ba/C-groepen.',
    pitfall: 'Een latere beschadiging rond de nek kan de doorsnede vertekenen.',
    source: 'Algoritme vraag 718, handleiding hamerbijltypen H en G',
  },
  '719': {
    short: 'Let op uitgewaaierde snede, uitgewaaierde nek en de aard van de verdikking bij het gat.',
    detail: 'Zo onderscheidt de bron type G van andere verwante hamerbijlen.',
    pitfall: 'Slijtage aan de snede kan de uitwaaiering minder duidelijk maken.',
    source: 'Algoritme vraag 719, handleiding hamerbijl type G',
  },
  '720': {
    short: 'Convexe bovenzijde, concave onderzijde en sterk versmalde nek openen type K/L.',
    detail: 'Daarna kijkt de bron naar de vorm van de nek om K en L te scheiden.',
    pitfall: 'Een gedeeltelijk afgebroken nek kan deze splitsing verstoren.',
    source: 'Algoritme vraag 720, handleiding hamerbijltypen K en L',
  },
  '721': {
    short: 'Een in hoogte verkleinde of genepen nek wijst op type L; anders blijft type K over.',
    detail: 'De nekmorfologie is hier doorslaggevend.',
    pitfall: 'Kijk niet alleen naar versmalling in breedte, maar ook naar hoogte.',
    source: 'Algoritme vraag 721, handleiding hamerbijltypen K en L',
  },
  '723': {
    short: 'Een scherpe verdikking bij de snede binnen de ronde-dwarsdoorsnede-route wijst op type Ba.',
    detail: 'Ontbreekt die scherpe verdikking, dan gaat de bron verder naar andere ronde hamerbijltypen.',
    pitfall: 'Een beschadigde verdikking kan te vlak lijken.',
    source: 'Algoritme vraag 723, handleiding hamerbijl type Ba',
  },
};

export function getSourceHint(questionId: string): SourceHint | null {
  return SOURCE_HINTS[questionId] ?? null;
}
